import os
func = input('Escreva a funcao: ')
X0 = input('X0: ')
X1 = input('X1: ')
IT = input('Iteracoes: ')
TAM = str(100)
arquivo = open('secante.py', 'w')
arquivo.write("")
arquivo.close()
cwd = os.path.join(os.getcwd(), "secante.py")
os.system('{} {}'.format('python', cwd))
