import os
funcao = input('Escreva a funcao: ')
x0 = input('X0: ')
x1 = input('X1: ')
eps = input('Epslon: ')
arquivo = open('secante.py', 'w')
arquivo.write("""import matplotlib.pyplot as plt\n\ndef biseccao (x, it):\n\tprint("# Bisecção")\n\tm = int((x[0]+x[1])/2)\n\n\tfor i in range(0, it):\n\t\tf1Value = fx(x[0])\n\t\tf2Value = fx(m)\n\t\tif f1Value!="?" and f2Value!="?" and fx(x[0])*fx(m)<0:\n\t\t\tx[1]=m\n\t\telse:\n\t\t\tx[0]=m\n\t\tprint("---- Intervalo da {} iteração: [{}, {}]".format(i+1, x[0], x[1]))\n\t\tm = int((x[0]+x[1])/2)\n\treturn x\n\ndef secant(x, f, it, eps, plotRange):\t\n\tprint("# Secante")\n\txAxis = []\n\tyAxis = []\n\troot = 0\n\tplotLeft = int(x[0]-plotRange)\n\tplotRight = int(x[1]+plotRange)\n\tfor i in range(plotLeft, plotRight):\n\t\tyValue = fx(i)\n\t\tif yValue!="?":\n\t\t\txAxis.append(i)\n\t\t\tyAxis.append(yValue)\n\n\tfuncao = " """+funcao+""" "\n\tplt.plot(xAxis, yAxis, label=funcao)\n\n\ttry:\n\t\tcont = 2 \n\t\twhile cont<it and abs(fx(len(x)-1)):\n\t\t\txValue = x[cont-1]-((f[cont-1]*(x[cont-1]-x[cont-2]))/(f[cont-1]-f[cont-2]))\n\t\t\tx.append(xValue)\n\t\t\tfValue = fx(xValue)\n\t\t\tf.append(fValue)\n\t\t\tcont+=1\n\n\texcept ZeroDivisionError:\n\t\tprint("ERRO #01: Divisao por zero")\n\texcept TypeError:\n\t\tprint("ERRO #02: TypeError")\n\t\troot = "?"\n\n\tfor i in range (2, len(f)):\n\t\tfSec(i, x[i-1], x[i], f[i-1], f[i], plotLeft, plotRight)\n\n\tif root!="?":\n\t\troot = str(x[len(x)-1])\n\n\tplt.title("{}, raiz = ".format(funcao) + root)\n\tplt.ylabel("f(x)")\n\tplt.xlabel("x")\n\tplt.legend()\n\tplt.grid(True)\n\tplt.show()\n\ndef fSec(i, x0, x1, f0, f1, plotLeft, plotRight):\n\ttry:\n\t\tm = (f1-f0)/(x1-x0)\n\t\txAxis = [x1]\n\t\tyAxis = [f1]\n\t\tfor x in range(plotLeft, plotRight):\n\t\t\ty = m*(x-xAxis[0])+yAxis[0]\n\t\t\txAxis.append(x)\n\t\t\tyAxis.append(y)\n\t\tlbl = str(i-1)+" iteração"\n\t\tplt.plot(xAxis, yAxis,"--", label = lbl)\n\n\texcept ZeroDivisionError:\n\t\tprint("ERRO #03: Divisao por zero")\n\ndef fx(x):\n\ttry:\n\t\treturn """+funcao+"""\n\n\texcept ZeroDivisionError:\n\t\tprint("ERRO #04: Divisao por zero")\n\t\treturn "?"\n\n\texcept TypeError:\n\t\tprint("ERRO #05: TypeError")\n\t\t\n\ndef main():\n\tx=["""+x0+""", """+x1+"""]\n\titSMax = 100\n\titB = 7\n\tplotRange = 1000\n\teps = """+eps+"""\n\t\n\tif fx(x[0])*fx(x[1])<0:\n\t\tx = biseccao(x, itB)\n\n\t\tf=[fx(x[0]), fx(x[1])]\n\n\t\tsecant(x, f, itSMax+1, eps, plotRange)\t\n\n\telse:\n\t\tprint("Nao existem raizes no intervalo dado")\n\nif __name__ == "__main__":\n    main()\n"""
)

arquivo.close()
cwd = os.path.join(os.getcwd(), "secante.py")
os.system('{} {}'.format('python', cwd))
